# Generated by Django 4.2.7 on 2023-11-14 19:06

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=150, verbose_name='псевдоним')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('comment', models.CharField(blank=True, max_length=400, null=True, verbose_name='комментарий')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='аватар')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='телефон')),
                ('sex', models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='Мужской пол', max_length=40)),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='супер пользователь')),
                ('hidden_prof', models.BooleanField(default=False, verbose_name='профиль скрыт')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='дата создания аккаунта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
