# Generated by Django 4.2.7 on 2023-11-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='length',
            field=models.PositiveIntegerField(choices=[(1, 'месяц'), (3, 'три месяца'), (6, 'шесть месяцев'), (12, 'двенадцать месяцев')], default=1, verbose_name='длительность'),
        ),
    ]
