# Generated by Django 4.2.7 on 2023-11-23 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subplan_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_own', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
    ]
