# Generated by Django 4.2.7 on 2023-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subplan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='subplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='о себе'),
        ),
    ]
