# Generated by Django 4.2.7 on 2023-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subplan_stripe_price_id_subplan_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID Stripe цена'),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ID Stripe продукт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='псевдоним'),
        ),
    ]
