# Generated by Django 4.2.7 on 2023-11-23 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(verbose_name='дата окончания подписки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_creator', to=settings.AUTH_USER_MODEL, verbose_name='создатель контента')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_sub', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='создатель контента')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'бесплатная подписка',
                'verbose_name_plural': 'бесплатные подписки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('stripe_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='id оплаты в stripe')),
                ('stripe_status', models.BooleanField(default=False, verbose_name='статус')),
                ('stripe_url', models.TextField(blank=True, null=True, verbose_name='url на платеж')),
                ('redirect_url', models.URLField(verbose_name='ссылка на прошлую страницу')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_own', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='subscription.paidsubscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
